# Known verbs and their correct POS tags (manual correction list)
KNOWN_VERBS = {
    "construct": "VB",
    "analyze": "VB",
    "analyse": "VB",
    "remember": "VB",
    "evaluate": "VB",
    "understand": "VB",
    "apply": "VB",
    "create": "VB",
    "what": "NULL",
    "describe": "VB",
    "be": "NULL",
    "do": "NULL",
    "is based": "NULL",
    "websites": "NULL",
    "\u201c": "NULL",
    "show\u2026": "NULL",
    "\u2013" : "NULL",
    "\u2026" : "NULL",
    "....": "NULL",
    "<": "NULL",
    "[": "NULL",
    "k": "NULL",
    "=": "NULL",
    "s": "NULL",
    "is": "NULL",
    "arabia": "NULL",
    "are": "NULL",
    "did": "NULL",
    "does": "NULL",
    "living" : "NULL",
    "helps" : "NULL",
    "help" : "NULL",
    "has" : "NULL",
    "falling" : "NULL",
    "x" : "NULL",
    "was" : "NULL",
    "homework" : "NULL",
    "please" : "NULL",
    "advanced" : "NULL",
    "based" : "NULL",
    "carry" : "NULL",
    "inform" : "NULL",
    "informs" : "NULL",
    "informing" : "NULL",
    "tolerate" : "NULL",
    "working" : "NULL",
    "lens" : "NULL",
    "facing" : "NULL",
    "look" : "NULL",
    "communicate" : "NULL",
    "flying" : "NULL",
    "pertaining" : "NULL",
    "setting" : "NULL",
    "includes" : "NULL",
    "knowing" : "NULL",
    "discharging" : "NULL",
    "aviation" : "NULL",
    "specifc" : "NULL",
    "live" : "NULL",
    "involving" : "NULL",
    "appropriate" : "NULL",
    "involved" : "NULL",
    "oriented" : "NULL",
    "cognitive" : "NULL",
    "nurturing" : "NULL",
    "covered" : "NULL",
    "dilemmas" : "NULL",
    "behaviour" : "NULL",
    "underlying" : "NULL",
    "introduced" : "NULL",
    "break" : "NULL",
    "meaning" : "NULL",
    "underpin" : "NULL",
    "existing" : "NULL",
    "looping" : "NULL",
    "focus" : "NULL",
    "navigation" : "NULL",
    "briefly" : "NULL",
    "know" : "NULL",
    "descending" : "NULL",
    "meant" : "NULL",
    "means" : "NULL",
    "correct" : "NULL",
    "put" : "NULL",
    "see" : "NULL",
    "take" : "NULL",
    "cut" : "NULL",
    "were" : "NULL",
    "done" : "NULL",
    "have" : "NULL",
    "deal" : "NULL",
    "according" : "NULL",
    "reducing" : "NULL",
    "include" : "NULL",
    "following" : "NULL",
    "sought" : "NULL",
    "settle" : "NULL",
    "synthesise" : "NULL",
    "pitch" : "NULL",
    "enable" : "NULL",
    "centered" : "NULL",
    "programs" : "NULL",
    "program" : "NULL",
    "took" : "NULL",
    "spoken" : "NULL",
    "exist" : "NULL",
    "purpose" : "NULL",
    "learned" : "NULL",
    "follow" : "NULL",
    "kill" : "NULL",
    "saw" : "NULL",
    "belong" : "NULL",
    "think" : "NULL",
    "ending" : "NULL",
    "happen" : "NULL",
    "shading" : "NULL",
    "running" : "NULL",
    "immersed" : "NULL",
    "occur" : "NULL",
    "answer" : "NULL",
    "lifestyles" : "NULL",
    "classroom" : "NULL",
    "yielded" : "NULL",
    "travelled" : "NULL",
    "finish" : "NULL",
    "curves" : "NULL",
    "occurred" : "NULL",
    "result" : "NULL",
    "coupling" : "NULL",
    "slows" : "NULL",
    "goes" : "NULL",
    "sinking" : "NULL",
    "geared" : "NULL",
    "sells" : "NULL",
    "sell" : "NULL",
    "saying" : "NULL",
    "says" : "NULL",
    "english" : "NULL",
    "crushing" : "NULL",
    "address" : "NULL",
    "call" : "NULL",
    "calls" : "NULL",
    "echoing" : "NULL",
    "rising" : "NULL",
    "concerning" : "NULL",
    "autonomy" : "NULL",
    "excluding" : "NULL",
    "aged" : "NULL",
    "rums" : "NULL",
    "known" : "NULL",
    "relative" : "NULL",
    "plumbing" : "NULL",
    "choose": "VB",
    "chooses": "VB",
    "chosen": "VB",
    "choosing": "VB",
    "chose": "VB",
    "define": "VB",
    "defines": "VB",
    "defined": "VB",
    "defining": "VB",
    "find": "VB",
    "finds": "VB",
    "found": "VB",
    "finding": "VB",
    "how": "NULL",
    "how's": "NULL",
    "label": "VB",
    "labels": "VB",
    "labeled": "VB",
    "labeling": "VB",
    "list": "VB",
    "lists": "VB",
    "listed": "VB",
    "listing": "VB",
    "match": "VB",
    "matches": "VB",
    "matched": "VB",
    "matching": "VB",
    "name": "VB",
    "names": "VB",
    "named": "VB",
    "naming": "VB",
    "omit": "VB",
    "omits": "VB",
    "omited": "VB",
    "omiting": "VB",
    "recall": "VB",
    "recalls": "VB",
    "recalled": "VB",
    "recalling": "VB",
    "spell": "VB",
    "spells": "VB",
    "spelled": "VB",
    "spelling": "VB",
    "tell": "VB",
    "tells": "VB",
    "told": "VB",
    "telling": "VB",
    "what's": "NULL",
    "when": "NULL",
    "when's": "NULL",
    "where": "NULL",
    "where's": "NULL",
    "which": "NULL",
    "which's": "NULL",
    "who": "NULL",
    "who's": "NULL",
    "why": "NULL",
    "why's": "NULL",
    "underline": "VB",
    "underlined": "VB",
    "underlining": "VB",
    "underlines": "VB",
    "tally": "VB",
    "tallying": "VB",
    "tallyed": "VB",
    "tallied": "VB",
    "talliestrace": "VB",
    "traced": "VB",
    "tracing": "VB",
    "traces": "VB",
    "bookmark": "VB",
    "bookmarked": "VB",
    "bookmarking": "VB",
    "bookmarks": "VB",
    "bullet-point": "VB",
    "bullet-pointed": "VB",
    "bullet-pointing": "VB",
    "bullet-points": "VB",
    "cite": "VB",
    "cited": "VB",
    "cites": "VB",
    "citing": "VB",
    "copy": "VB",
    "copies": "VB",
    "copied": "VB",
    "copying": "VB",
    "duplicate": "VB",
    "duplicates": "VB",
    "duplicated": "VB",
    "duplicating": "VB",
    "enumerate": "VB",
    "enumerates": "VB",
    "enumerated": "VB",
    "enumerating": "VB",
    "google": "VB",
    "googles": "VB",
    "googled": "VB",
    "googling": "VB",
    "highlight": "VB",
    "highlights": "VB",
    "highlighted": "VB",
    "highlighting": "VB",
    "identify": "VB",
    "identifies": "VB",
    "identified": "VB",
    "identifying": "VB",
    "index": "VB",
    "indexes": "VB",
    "indexed": "VB",
    "indexing": "VB",
    "indicate": "VB",
    "indicates": "VB",
    "indicated": "VB",
    "indicating": "VB",
    "listen": "VB",
    "listens": "VB",
    "listened": "VB",
    "listening": "VB",
    "locate": "VB",
    "locates": "VB",
    "located": "VB",
    "locating": "VB",
    "meet": "VB",
    "meets": "VB",
    "meeted": "VB",
    "meeting": "VB",
    "memorize": "VB",
    "memorizes": "VB",
    "memorized": "VB",
    "memorizing": "VB",
    "point": "VB",
    "points": "VB",
    "pointed": "VB",
    "pointing": "VB",
    "quote": "VB",
    "quotes": "VB",
    "quoted": "VB",
    "quoting": "VB",
    "read": "VB",
    "reads": "VB",
    "readed": "VB",
    "reading": "VB",
    "recite": "VB",
    "recites": "VB",
    "recited": "VB",
    "reciting": "VB",
    "recognize": "VB",
    "recognizes": "VB",
    "recognized": "VB",
    "recognizing": "VB",
    "record": "VB",
    "records": "VB",
    "recorded": "VB",
    "recording": "VB",
    "repeat": "VB",
    "repeats": "VB",
    "repeated": "VB",
    "repeating": "VB",
    "reproduce": "VB",
    "reproduces": "VB",
    "reproduced": "VB",
    "reproducing": "VB",
    "retrieve": "VB",
    "retrieves": "VB",
    "retrieved": "VB",
    "retrieving": "VB",
    "review": "VB",
    "reviews": "VB",
    "reviewed": "VB",
    "reviewing": "VB",
    "search": "VB",
    "searchs": "VB",
    "searched": "VB",
    "searching": "VB",
    "state": "VB",
    "states": "VB",
    "stated": "VB",
    "stating": "VB",
    "study": "VB",
    "studys": "VB",
    "studyed": "VB",
    "studying": "VB",
    "acquire": "VB",
    "acquired": "VB",
    "acquires": "VB",
    "acquiring": "VB",
    "add": "VB",
    "added": "VB",
    "adding": "VB",
    "adds": "VB",
    "annotate": "VB",
    "annotated": "VB",
    "annotates": "VB",
    "annotating": "VB",
    "approximate": "VB",
    "approximated": "VB",
    "approximates": "VB",
    "approximating": "VB",
    "approximately": "VB",
    "associate": "VB",
    "associated": "VB",
    "associates": "VB",
    "associating": "VB",
    "clarify": "VB",
    "clarifies": "VB",
    "clarified": "VB",
    "clarifying": "VB",
    "convert": "VB",
    "converted": "VB",
    "converting": "VB",
    "converts": "VB",
    "described": "VB",
    "describes": "VB",
    "describing": "VB",
    "detail": "VB",
    "detailed": "VB",
    "detailing": "VB",
    "details": "VB",
    "example": "VB",
    "examples": "VB",
    "exampled": "VB",
    "exampling": "VB",
    "exemplify": "VB",
    "exemplifys": "VB",
    "exemplified": "VB",
    "exemplifying": "VB",
    "explain": "VB",
    "explained": "VB",
    "explaining": "VB",
    "explains": "VB",
    "extend": "VB",
    "extended": "VB",
    "extending": "VB",
    "extends": "VB",
    "extrapolate": "VB",
    "extrapolated": "VB",
    "extrapolates": "VB",
    "extrapolating": "VB",
    "gather": "VB",
    "gathered": "VB",
    "gathering": "VB",
    "gathers": "VB",
    "give": "VB",
    "gives": "VB",
    "gave": "VB",
    "giving": "VB",
    "given": "VB",
    "give example": "VB",
    "give examples": "VB",
    "gave example": "VB",
    "gave examples": "VB",
    "giving example": "VB",
    "giving examples": "VB",
    "interact": "VB",
    "interacted": "VB",
    "interacting": "VB",
    "interacts": "VB",
    "journal": "VB",
    "journals": "VB",
    "journaled": "VB",
    "journaling": "VB",
    "link": "VB",
    "linked": "VB",
    "links": "VB",
    "linking": "VB",
    "observe": "VB",
    "observed": "VB",
    "observes": "VB",
    "observing": "VB",
    "outline": "VB",
    "outlined": "VB",
    "outlines": "VB",
    "outlining": "VB",
    "paraphrase": "VB",
    "paraphrased": "VB",
    "paraphrases": "VB",
    "paraphrasing": "VB",
    "picture graphically": "VB",
    "pictures graphically": "VB",
    "pictured graphically": "VB",
    "picturing graphically": "VB",
    "pictures": "VB",
    "pictured": "VB",
    "picturing": "VB",
    "relate": "VB",
    "related": "VB",
    "relates": "VB",
    "relating": "VB",
    "rephrase": "VB",
    "rephrased": "VB",
    "rephrases": "VB",
    "rephrasing": "VB",
    "subtract": "VB",
    "subtracted": "VB",
    "subtracting": "VB",
    "subtracts": "VB",
    "summarize": "VB",
    "summarized": "VB",
    "summarizes": "VB",
    "summarizing": "VB",
    "tag": "VB",
    "tags": "VB",
    "tagged": "VB",
    "tagging": "VB",
    "tweet": "VB",
    "tweets": "VB",
    "tweeted": "VB",
    "tweeting": "VB",
    "visualize": "VB",
    "visualized": "VB",
    "visualizes": "VB",
    "visualizing": "VB",
    "act out": "VB",
    "acts out": "VB",
    "acted out": "VB",
    "acting out": "VB",
    "allocate": "VB",
    "allocates": "VB",
    "allocated": "VB",
    "allocating": "VB",
    "alphabetize": "VB",
    "alphabetizes": "VB",
    "alphabetized": "VB",
    "alphabetizing": "VB",
    "amend": "VB",
    "amends": "VB",
    "amended": "VB",
    "amending": "VB",
    "applys": "VB",
    "applyed": "VB",
    "applying": "VB",
    "articulate": "VB",
    "articulates": "VB",
    "articulated": "VB",
    "articulating": "VB",
    "ascertain": "VB",
    "ascertains": "VB",
    "ascertained": "VB",
    "ascertaining": "VB",
    "assign": "VB",
    "assigns": "VB",
    "assigned": "VB",
    "assigning": "VB",
    "attain": "VB",
    "attains": "VB",
    "attained": "VB",
    "attaining": "VB",
    "avoid": "VB",
    "avoids": "VB",
    "avoided": "VB",
    "avoiding": "VB",
    "back": "VB",
    "backs": "VB",
    "backed": "VB",
    "backing": "VB",
    "back up": "VB",
    "backs up": "VB",
    "backed up": "VB",
    "backing up": "VB",
    "calculate": "VB",
    "calculates": "VB",
    "calculated": "VB",
    "calculating": "VB",
    "capture": "VB",
    "captures": "VB",
    "captured": "VB",
    "capturing": "VB",
    "change": "VB",
    "changes": "VB",
    "changed": "VB",
    "changing": "VB",
    "chart": "VB",
    "charts": "VB",
    "charted": "VB",
    "charting": "VB",
    "compute": "VB",
    "computes": "VB",
    "computed": "VB",
    "computing": "VB",
    "concatenate": "VB",
    "concatenates": "VB",
    "concatenated": "VB",
    "concatenating": "VB",
    "conduct": "VB",
    "conducts": "VB",
    "conducted": "VB",
    "conducting": "VB",
    "consult": "VB",
    "consults": "VB",
    "consulted": "VB",
    "consulting": "VB",
    "convey": "VB",
    "conveys": "VB",
    "conveyed": "VB",
    "conveying": "VB",
    "coordinate": "VB",
    "coordinates": "VB",
    "coordinated": "VB",
    "coordinating": "VB",
    "customize": "VB",
    "customizes": "VB",
    "customized": "VB",
    "customizing": "VB",
    "deliver": "VB",
    "delivers": "VB",
    "delivered": "VB",
    "delivering": "VB",
    "demonstrate": "VB",
    "demonstrates": "VB",
    "demonstrated": "VB",
    "demonstrating": "VB",
    "depreciate": "VB",
    "depreciates": "VB",
    "depreciated": "VB",
    "depreciating": "VB",
    "derive": "VB",
    "derives": "VB",
    "derived": "VB",
    "deriving": "VB",
    "determine": "VB",
    "determines": "VB",
    "determined": "VB",
    "determining": "VB",
    "diminish": "VB",
    "diminishs": "VB",
    "diminished": "VB",
    "diminishing": "VB",
    "discover": "VB",
    "discovers": "VB",
    "discovered": "VB",
    "discovering": "VB",
    "display": "VB",
    "displays": "VB",
    "displayed": "VB",
    "displaying": "VB",
    "divide": "VB",
    "divides": "VB",
    "divided": "VB",
    "dividing": "VB",
    "dramatize": "VB",
    "dramatizes": "VB",
    "dramatized": "VB",
    "dramatizing": "VB",
    "draw": "VB",
    "draws": "VB",
    "drawed": "VB",
    "drawing": "VB",
    "employ": "VB",
    "employs": "VB",
    "employed": "VB",
    "employing": "VB",
    "engineer": "VB",
    "engineers": "VB",
    "engineered": "VB",
    "engineering": "VB",
    "estimate": "VB",
    "estimated": "VB",
    "estimates": "VB",
    "estimating": "VB",
    "examine": "VB",
    "examines": "VB",
    "examined": "VB",
    "examining": "VB",
    "execute": "VB",
    "executes": "VB",
    "executed": "VB",
    "executing": "VB",
    "exercise": "VB",
    "exercises": "VB",
    "exercised": "VB",
    "exercising": "VB",
    "expand": "VB",
    "expands": "VB",
    "expanded": "VB",
    "expanding": "VB",
    "experiment": "VB",
    "experiments": "VB",
    "experimented": "VB",
    "experimenting": "VB",
    "experiment with": "VB",
    "experiments with": "VB",
    "experimented with": "VB",
    "experimenting with": "VB",
    "expose": "VB",
    "exposes": "VB",
    "exposed": "VB",
    "exposing": "VB",
    "express": "VB",
    "expresss": "VB",
    "expressed": "VB",
    "expressing": "VB",
    "figure": "VB",
    "figures": "VB",
    "figured": "VB",
    "figuring": "VB",
    "graph": "VB",
    "graphs": "VB",
    "graphed": "VB",
    "graphing": "VB",
    "guide": "VB",
    "guides": "VB",
    "guided": "VB",
    "guiding": "VB",
    "hack": "VB",
    "hacks": "VB",
    "hacked": "VB",
    "hacking": "VB",
    "handle": "VB",
    "handles": "VB",
    "handled": "VB",
    "handling": "VB",
    "illustrate": "VB",
    "illustrates": "VB",
    "illustrated": "VB",
    "illustrating": "VB",
    "implement": "VB",
    "implements": "VB",
    "implemented": "VB",
    "implementing": "VB",
    "interconvert": "VB",
    "interconverts": "VB",
    "interconverted": "VB",
    "interconverting": "VB",
    "interview": "VB",
    "interviews": "VB",
    "interviewed": "VB",
    "interviewing": "VB",
    "load": "VB",
    "loads": "VB",
    "loaded": "VB",
    "loading": "VB",
    "make use of": "VB",
    "makes use of": "VB",
    "made use of": "VB",
    "making use of": "VB",
    "manage": "VB",
    "managed": "VB",
    "managing": "VB",
    "manages": "VB",
    "manipulate": "VB",
    "manipulates": "VB",
    "manipulated": "VB",
    "manipulating": "VB",
    "modify": "VB",
    "modifies": "VB",
    "modified": "VB",
    "modifying": "VB",
    "multiply": "VB",
    "multiplies": "VB",
    "multiplied": "VB",
    "multiplying": "VB",
    "obtain": "VB",
    "obtains": "VB",
    "obtained": "VB",
    "obtaining": "VB",
    "operate": "VB",
    "operates": "VB",
    "operated": "VB",
    "operating": "VB",
    "paint": "VB",
    "paints": "VB",
    "painted": "VB",
    "painting": "VB",
    "perform": "VB",
    "performs": "VB",
    "performed": "VB",
    "performing": "VB",
    "personalize": "VB",
    "personalizes": "VB",
    "personalized": "VB",
    "personalizing": "VB",
    "play": "VB",
    "plays": "VB",
    "played": "VB",
    "playing": "VB",
    "plot": "VB",
    "plots": "VB",
    "plotted": "VB",
    "plotting": "VB",
    "practice": "VB",
    "practices": "VB",
    "practiced": "VB",
    "practicing": "VB",
    "prepare": "VB",
    "prepares": "VB",
    "prepared": "VB",
    "preparing": "VB",
    "present": "VB",
    "presents": "VB",
    "presented": "VB",
    "presenting": "VB",
    "price": "VB",
    "prices": "VB",
    "priced": "VB",
    "pricing": "VB",
    "process": "VB",
    "processs": "VB",
    "processed": "VB",
    "processing": "VB",
    "project": "VB",
    "projects": "VB",
    "projected": "VB",
    "projecting": "VB",
    "protect": "VB",
    "protects": "VB",
    "protected": "VB",
    "protecting": "VB",
    "provide": "VB",
    "provides": "VB",
    "provided": "VB",
    "providing": "VB",
    "reenact": "VB",
    "reenacts": "VB",
    "reenacted": "VB",
    "reenacting": "VB",
    "round off": "VB",
    "rounds off": "VB",
    "rounded off": "VB",
    "rounding off": "VB",
    "sequence": "VB",
    "sequences": "VB",
    "sequenced": "VB",
    "sequencing": "VB",
    "show": "VB",
    "shows": "VB",
    "showed": "VB",
    "showing": "VB",
    "shown": "VB",
    "simplify": "VB",
    "simplifies": "VB",
    "simplifyed": "VB",
    "simplifying": "VB",
    "simulate": "VB",
    "simulates": "VB",
    "simulated": "VB",
    "simulating": "VB",
    "sketch": "VB",
    "sketches": "VB",
    "sketched": "VB",
    "sketching": "VB",
    "solve": "VB",
    "solves": "VB",
    "solved": "VB",
    "solving": "VB",
    "subscribe": "VB",
    "subscribes": "VB",
    "subscribed": "VB",
    "subscribing": "VB",
    "unsubscribe": "VB",
    "unsubscribes": "VB",
    "unsubscribed": "VB",
    "unsubscribing": "VB",
    "tabulate": "VB",
    "tabulates": "VB",
    "tabulated": "VB",
    "tabulating": "VB",
    "transcribe": "VB",
    "transcribes": "VB",
    "transcribed": "VB",
    "transcribing": "VB",
    "translate": "VB",
    "translates": "VB",
    "translated": "VB",
    "translating": "VB",
    "use": "VB",
    "uses": "VB",
    "used": "VB",
    "using": "VB",
    "utilize": "VB",
    "utilizes": "VB",
    "utilized": "VB",
    "utilizing": "VB",
    "accept": "VB",
    "accepted": "VB",
    "accepting": "VB",
    "accepts": "VB",
    "administer": "VB",
    "administered": "VB",
    "administering": "VB",
    "administers": "VB",
    "advertise": "VB",
    "advertised": "VB",
    "advertises": "VB",
    "advertising": "VB",
    "allow": "VB",
    "allowed": "VB",
    "allowing": "VB",
    "allows": "VB",
    "analyzed": "VB",
    "analyzes": "VB",
    "analyzing": "VB",
    "attribute": "VB",
    "attributed": "VB",
    "attributes": "VB",
    "attributing": "VB",
    "audit": "VB",
    "audited": "VB",
    "auditing": "VB",
    "audits": "VB",
    "blueprint": "VB",
    "blueprinted": "VB",
    "blueprinting": "VB",
    "blueprints": "VB",
    "breadboard": "VB",
    "breadboarded": "VB",
    "breadboarding": "VB",
    "breadboards": "VB",
    "break down": "VB",
    "breaks down": "VB",
    "broken down": "VB",
    "breaking down": "VB",
    "categorize": "VB",
    "categorized": "VB",
    "categorizes": "VB",
    "categorizing": "VB",
    "characterize": "VB",
    "characterized": "VB",
    "characterizes": "VB",
    "characterizing": "VB",
    "check": "VB",
    "checked": "VB",
    "checking": "VB",
    "checks": "VB",
    "chunk": "VB",
    "chunked": "VB",
    "chunking": "VB",
    "chunks": "VB",
    "classify": "VB",
    "classified": "VB",
    "classifying": "VB",
    "classifys": "VB",
    "compare": "VB",
    "compared": "VB",
    "compares": "VB",
    "comparing": "VB",
    "confirm": "VB",
    "confirmed": "VB",
    "confirming": "VB",
    "confirms": "VB",
    "consolidate": "VB",
    "consolidated": "VB",
    "consolidates": "VB",
    "consolidating": "VB",
    "contrast": "VB",
    "contrasted": "VB",
    "contrasting": "VB",
    "contrasts": "VB",
    "correlate": "VB",
    "correlated": "VB",
    "correlating": "VB",
    "correlates": "VB",
    "corroborate": "VB",
    "corroborated": "VB",
    "corroborates": "VB",
    "corroborating": "VB",
    "deconstruct": "VB",
    "deconstructed": "VB",
    "deconstructing": "VB",
    "deconstructs": "VB",
    "deduce": "VB",
    "deduced": "VB",
    "deduces": "VB",
    "deducing": "VB",
    "delegate": "VB",
    "delegated": "VB",
    "delegating": "VB",
    "delegates": "VB",
    "detect": "VB",
    "detected": "VB",
    "detecting": "VB",
    "detects": "VB",
    "diagnose": "VB",
    "diagnosed": "VB",
    "diagnosing": "VB",
    "diagnoses": "VB",
    "differentiate": "VB",
    "differentiated": "VB",
    "differentiating": "VB",
    "differentiates": "VB",
    "discriminate": "VB",
    "discriminated": "VB",
    "discriminating": "VB",
    "discriminates": "VB",
    "dissect": "VB",
    "dissected": "VB",
    "dissecting": "VB",
    "dissects": "VB",
    "distinguish": "VB",
    "distinguished": "VB",
    "distinguishing": "VB",
    "distinguishes": "VB",
    "document": "VB",
    "documented": "VB",
    "documenting": "VB",
    "documents": "VB",
    "elaborate": "VB",
    "elaborated": "VB",
    "elaborates": "VB",
    "elaborating": "VB",
    "ensnare": "VB",
    "ensnared": "VB",
    "ensnaring": "VB",
    "ensnares": "VB",
    "explore": "VB",
    "explored": "VB",
    "exploring": "VB",
    "explores": "VB",
    "factor": "VB",
    "factored": "VB",
    "factoring": "VB",
    "factors": "VB",
    "figure out": "VB",
    "figures out": "VB",
    "figured out": "VB",
    "figuring out": "VB",
    "file": "VB",
    "filed": "VB",
    "filing": "VB",
    "files": "VB",
    "function": "VB",
    "functioned": "VB",
    "functioning": "VB",
    "functions": "VB",
    "group": "VB",
    "grouped": "VB",
    "grouping": "VB",
    "groups": "VB",
    "infer": "VB",
    "inferred": "VB",
    "inferring": "VB",
    "infers": "VB",
    "inference": "VB",
    "inferences": "VB",
    "inferenced": "VB",
    "inferencing": "VB",
    "inspect": "VB",
    "inspected": "VB",
    "inspecting": "VB",
    "inspects": "VB",
    "integrate": "VB",
    "integrated": "VB",
    "integrating": "VB",
    "integrates": "VB",
    "interpret": "VB",
    "interpreted": "VB",
    "interpreting": "VB",
    "interprets": "VB",
    "inventory": "VB",
    "inventoried": "VB",
    "inventorying": "VB",
    "inventories": "VB",
    "investigate": "VB",
    "investigated": "VB",
    "investigating": "VB",
    "investigates": "VB",
    "layout": "VB",
    "layouts": "VB",
    "layouted": "VB",
    "layouting": "VB",
    "mash": "VB",
    "mashed": "VB",
    "mashing": "VB",
    "mashes": "VB",
    "maximize": "VB",
    "maximized": "VB",
    "maximizing": "VB",
    "maximizes": "VB",
    "mind-map": "VB",
    "mind-mapped": "VB",
    "mind-mapping": "VB",
    "mind-maps": "VB",
    "minimize": "VB",
    "minimized": "VB",
    "minimizing": "VB",
    "minimizes": "VB",
    "motive": "VB",
    "motived": "VB",
    "motiving": "VB",
    "motives": "VB",
    "optimize": "VB",
    "optimized": "VB",
    "optimizing": "VB",
    "optimizes": "VB",
    "order": "VB",
    "ordered": "VB",
    "ordering": "VB",
    "orders": "VB",
    "organize": "VB",
    "organizes": "VB",
    "organized": "VB",
    "organizing": "VB",
    "point out": "VB",
    "point outs": "VB",
    "point outed": "VB",
    "point outing": "VB",
    "predict": "VB",
    "predicted": "VB",
    "predicting": "VB",
    "predicts": "VB",
    "proofread": "VB",
    "proofreaded": "VB",
    "proofreading": "VB",
    "proofreads": "VB",
    "query": "VB",
    "queryed": "VB",
    "querying": "VB",
    "querys": "VB",
    "question": "VB",
    "questioned": "VB",
    "questioning": "VB",
    "questions": "VB",
    "relationship": "VB",
    "relationshiped": "VB",
    "relationshiping": "VB",
    "relationships": "VB",
    "select": "VB",
    "selected": "VB",
    "selecting": "VB",
    "selects": "VB",
    "separate": "VB",
    "separated": "VB",
    "separating": "VB",
    "separates": "VB",
    "size up": "VB",
    "size ups": "VB",
    "size uped": "VB",
    "size uping": "VB",
    "structure": "VB",
    "structured": "VB",
    "structuring": "VB",
    "structures": "VB",
    "subdivide": "VB",
    "subdivided": "VB",
    "subdividing": "VB",
    "subdivides": "VB",
    "survey": "VB",
    "surveyed": "VB",
    "surveying": "VB",
    "surveys": "VB",
    "take part in": "VB",
    "takes part in": "VB",
    "took part in": "VB",
    "taking part in": "VB",
    "test for": "VB",
    "tests for": "VB",
    "tested for": "VB",
    "testing for": "VB",
    "theme": "VB",
    "themed": "VB",
    "theming": "VB",
    "themes": "VB",
    "train": "VB",
    "trained": "VB",
    "training": "VB",
    "trains": "VB",
    "transform": "VB",
    "transformed": "VB",
    "transforming": "VB",
    "transforms": "VB",
    "troubleshoot": "VB",
    "troubleshooted": "VB",
    "troubleshooting": "VB",
    "troubleshoots": "VB",
    "advise": "VB",
    "advised": "VB",
    "advises": "VB",
    "advising": "VB",
    "agree": "VB",
    "agreed": "VB",
    "agrees": "VB",
    "agreeing": "VB",
    "appraise": "VB",
    "appraised": "VB",
    "appraises": "VB",
    "appraising": "VB",
    "argue": "VB",
    "argued": "VB",
    "argues": "VB",
    "arguing": "VB",
    "assess": "VB",
    "assessed": "VB",
    "assessing": "VB",
    "assesses": "VB",
    "authenticate": "VB",
    "authenticated": "VB",
    "authenticates": "VB",
    "authenticating": "VB",
    "award": "VB",
    "awarded": "VB",
    "awarding": "VB",
    "awards": "VB",
    "comment": "VB",
    "commented": "VB",
    "commenting": "VB",
    "comments": "VB",
    "conclude": "VB",
    "concluded": "VB",
    "concludes": "VB",
    "concluding": "VB",
    "counsel": "VB",
    "counseled": "VB",
    "counseling": "VB",
    "counsels": "VB",
    "criteria": "VB",
    "criteriaed": "VB",
    "criteriaing": "VB",
    "criterias": "VB",
    "criticize": "VB",
    "criticized": "VB",
    "criticizes": "VB",
    "criticizing": "VB",
    "critique": "VB",
    "critiqued": "VB",
    "critiques": "VB",
    "critiquing": "VB",
    "debate": "VB",
    "debated": "VB",
    "debates": "VB",
    "debating": "VB",
    "decide": "VB",
    "decided": "VB",
    "decides": "VB",
    "deciding": "VB",
    "deduct": "VB",
    "deducted": "VB",
    "deducting": "VB",
    "deducts": "VB",
    "defend": "VB",
    "defended": "VB",
    "defending": "VB",
    "defends": "VB",
    "discuss": "VB",
    "discussed": "VB",
    "discussing": "VB",
    "discusses": "VB",
    "disprove": "VB",
    "disproved": "VB",
    "disproving": "VB",
    "disproves": "VB",
    "editorialize": "VB",
    "editorialized": "VB",
    "editorializes": "VB",
    "editorializing": "VB",
    "evaluated": "VB",
    "evaluating": "VB",
    "evaluates": "VB",
    "generalize": "VB",
    "generalized": "VB",
    "generalizes": "VB",
    "generalizing": "VB",
    "grade": "VB",
    "graded": "VB",
    "grading": "VB",
    "grades": "VB",
    "hire": "VB",
    "hired": "VB",
    "hiring": "VB",
    "hires": "VB",
    "importance": "VB",
    "importanced": "VB",
    "importancing": "VB",
    "importances": "VB",
    "influence": "VB",
    "influenced": "VB",
    "influencing": "VB",
    "influences": "VB",
    "judge": "VB",
    "judged": "VB",
    "judging": "VB",
    "judges": "VB",
    "justify": "VB",
    "justified": "VB",
    "justifying": "VB",
    "justifies": "VB",
    "mark": "VB",
    "marked": "VB",
    "marking": "VB",
    "marks": "VB",
    "measure": "VB",
    "measured": "VB",
    "measuring": "VB",
    "measures": "VB",
    "moderate": "VB",
    "moderated": "VB",
    "moderating": "VB",
    "moderates": "VB",
    "opinion": "VB",
    "opinioned": "VB",
    "opinioning": "VB",
    "opinions": "VB",
    "perceive": "VB",
    "perceived": "VB",
    "perceiving": "VB",
    "perceives": "VB",
    "post": "VB",
    "posted": "VB",
    "posting": "VB",
    "posts": "VB",
    "prescribe": "VB",
    "prescribed": "VB",
    "prescribing": "VB",
    "prescribes": "VB",
    "preserve": "VB",
    "preserved": "VB",
    "preserving": "VB",
    "preserves": "VB",
    "prioritize": "VB",
    "prioritized": "VB",
    "prioritizing": "VB",
    "prioritizes": "VB",
    "prove": "VB",
    "proved": "VB",
    "proving": "VB",
    "proves": "VB",
    "rank": "VB",
    "ranked": "VB",
    "ranking": "VB",
    "ranks": "VB",
    "rate": "VB",
    "rated": "VB",
    "rating": "VB",
    "rates": "VB",
    "recommend": "VB",
    "recommended": "VB",
    "recommending": "VB",
    "recommends": "VB",
    "reconcile": "VB",
    "reconciled": "VB",
    "reconciling": "VB",
    "reconciles": "VB",
    "reflect": "VB",
    "reflected": "VB",
    "reflecting": "VB",
    "reflects": "VB",
    "release": "VB",
    "released": "VB",
    "releasing": "VB",
    "releases": "VB",
    "resolve": "VB",
    "resolved": "VB",
    "resolving": "VB",
    "resolves": "VB",
    "rule on": "VB",
    "ruled on": "VB",
    "ruling on": "VB",
    "rules on": "VB",
    "score": "VB",
    "scored": "VB",
    "scoring": "VB",
    "scores": "VB",
    "support": "VB",
    "supported": "VB",
    "supporting": "VB",
    "supports": "VB",
    "test": "VB",
    "tested": "VB",
    "testing": "VB",
    "tests": "VB",
    "uphold": "VB",
    "upholded": "VB",
    "upholding": "VB",
    "upholds": "VB",
    "validate": "VB",
    "validated": "VB",
    "validating": "VB",
    "validates": "VB",
    "value": "VB",
    "valued": "VB",
    "valuing": "VB",
    "values": "VB",
    "verify": "VB",
    "verified": "VB",
    "verifying": "VB",
    "verifies": "VB",
    "weigh": "VB",
    "weighed": "VB",
    "weighing": "VB",
    "weighs": "VB",
    "abstract": "VB",
    "abstracted": "VB",
    "abstracting": "VB",
    "abstracts": "VB",
    "adapt": "VB",
    "adapted": "VB",
    "adapting": "VB",
    "adapts": "VB",
    "animate": "VB",
    "animated": "VB",
    "animating": "VB",
    "animates": "VB",
    "anticipate": "VB",
    "anticipated": "VB",
    "anticipating": "VB",
    "anticipates": "VB",
    "arbitrate": "VB",
    "arbitrated": "VB",
    "arbitrating": "VB",
    "arbitrates": "VB",
    "arrange": "VB",
    "arranged": "VB",
    "arranging": "VB",
    "arranges": "VB",
    "assemble": "VB",
    "assembled": "VB",
    "assembling": "VB",
    "assembles": "VB",
    "blog": "VB",
    "blogged": "VB",
    "blogging": "VB",
    "blogs": "VB",
    "brief": "VB",
    "briefed": "VB",
    "briefing": "VB",
    "briefs": "VB",
    "budget": "VB",
    "budgeted": "VB",
    "budgeting": "VB",
    "budgets": "VB",
    "build": "VB",
    "built": "VB",
    "building": "VB",
    "builds": "VB",
    "code": "VB",
    "coded": "VB",
    "coding": "VB",
    "codes": "VB",
    "collaborate": "VB",
    "collaborated": "VB",
    "collaborating": "VB",
    "collaborates": "VB",
    "collect": "VB",
    "collected": "VB",
    "collecting": "VB",
    "collects": "VB",
    "combine": "VB",
    "combined": "VB",
    "combining": "VB",
    "combines": "VB",
    "compile": "VB",
    "compiled": "VB",
    "compiling": "VB",
    "compiles": "VB",
    "compose": "VB",
    "composed": "VB",
    "composing": "VB",
    "composes": "VB",
    "constructed": "VB",
    "constructing": "VB",
    "constructs": "VB",
    "cope": "VB",
    "coped": "VB",
    "coping": "VB",
    "copes": "VB",
    "correspond": "VB",
    "corresponded": "VB",
    "corresponding": "VB",
    "corresponds": "VB",
    "created": "VB",
    "creating": "VB",
    "creates": "VB",
    "cultivate": "VB",
    "cultivated": "VB",
    "cultivating": "VB",
    "cultivates": "VB",
    "debug": "VB",
    "debugged": "VB",
    "debugging": "VB",
    "debugs": "VB",
    "delete": "VB",
    "deleted": "VB",
    "deleting": "VB",
    "deletes": "VB",
    "depict": "VB",
    "depicted": "VB",
    "depicting": "VB",
    "depicts": "VB",
    "design": "VB",
    "designed": "VB",
    "designing": "VB",
    "designs": "VB",
    "develop": "VB",
    "developed": "VB",
    "developing": "VB",
    "develops": "VB",
    "devise": "VB",
    "devised": "VB",
    "devising": "VB",
    "devises": "VB",
    "dictate": "VB",
    "dictated": "VB",
    "dictating": "VB",
    "dictates": "VB",
    "direct": "VB",
    "directed": "VB",
    "directing": "VB",
    "directs": "VB",
    "enhance": "VB",
    "enhanced": "VB",
    "enhancing": "VB",
    "enhances": "VB",
    "facilitate": "VB",
    "facilitated": "VB",
    "facilitating": "VB",
    "facilitates": "VB",
    "film": "NULL",
    "filmed": "NULL",
    "filming": "NULL",
    "films": "NULL",
    "format": "VB",
    "formatted": "VB",
    "formatting": "VB",
    "formats": "VB",
    "formulate": "VB",
    "formulated": "VB",
    "formulating": "VB",
    "formulates": "VB",
    "generate": "VB",
    "generated": "VB",
    "generating": "VB",
    "generates": "VB",
    "happened": "VB",
    "happening": "VB",
    "happens": "VB",
    "hypothesize": "VB",
    "hypothesized": "VB",
    "hypothesizing": "VB",
    "hypothesizes": "VB",
    "imagine": "VB",
    "imagined": "VB",
    "imagining": "VB",
    "imagines": "VB",
    "import": "VB",
    "imported": "VB",
    "importing": "VB",
    "imports": "VB",
    "improve": "VB",
    "improved": "VB",
    "improving": "VB",
    "improves": "VB",
    "incorporate": "VB",
    "incorporated": "VB",
    "incorporating": "VB",
    "incorporates": "VB",
    "interface": "VB",
    "interfaced": "VB",
    "interfacing": "VB",
    "interfaces": "VB",
    "invent": "VB",
    "invented": "VB",
    "inventing": "VB",
    "invents": "VB",
    "join": "VB",
    "joined": "VB",
    "joining": "VB",
    "joins": "VB",
    "lead": "VB",
    "led": "VB",
    "leading": "VB",
    "leads": "VB",
    "lecture": "VB",
    "lectured": "VB",
    "lecturing": "VB",
    "lectures": "VB",
    "make up": "VB",
    "made up": "VB",
    "making up": "VB",
    "makes up": "VB",
    "mix": "VB",
    "mixed": "VB",
    "mixing": "VB",
    "mixes": "VB",
    "model": "VB",
    "modeled": "VB",
    "modelling": "VB",
    "models": "VB",
    "negotiate": "VB",
    "negotiated": "VB",
    "negotiating": "VB",
    "negotiates": "VB",
    "network": "VB",
    "networked": "VB",
    "networking": "VB",
    "networks": "VB",
    "original": "VB",
    "originals": "VB",
    "originate": "VB",
    "originated": "VB",
    "originating": "VB",
    "originates": "VB",
    "overhaul": "VB",
    "overhauled": "VB",
    "overhauling": "VB",
    "overhauls": "VB",
    "plan": "VB",
    "planned": "VB",
    "planning": "VB",
    "plans": "VB",
    "podcast": "VB",
    "podcasted": "VB",
    "podcasting": "VB",
    "podcasts": "VB",
    "portray": "VB",
    "portrayed": "VB",
    "portraying": "VB",
    "portrays": "VB",
    "produce": "VB",
    "produced": "VB",
    "producing": "VB",
    "produces": "VB",
    "propose": "VB",
    "proposed": "VB",
    "proposing": "VB",
    "proposes": "VB",
    "rearrange": "VB",
    "rearranged": "VB",
    "rearranging": "VB",
    "rearranges": "VB",
    "reconstruct": "VB",
    "reconstructed": "VB",
    "reconstructing": "VB",
    "reconstructs": "VB",
    "revise": "VB",
    "revised": "VB",
    "revising": "VB",
    "revises": "VB",
    "rewrite": "VB",
    "rewritten": "VB",
    "rewriting": "VB",
    "rewrites": "VB",
    "role play": "VB",
    "role played": "VB",
    "role playing": "VB",
    "role plays": "VB",
    "role-playing": "VB",
    "role-played": "VB",
    "role-plays": "VB",
    "solution": "VB",
    "solutions": "VB",
    "solutioned": "VB",
    "solutioning": "VB",
    "specify": "VB",
    "specified": "VB",
    "specifying": "VB",
    "specifies": "VB",
    "suppose": "VB",
    "supposed": "VB",
    "supposing": "VB",
    "supposes": "VB",
    "teach": "VB",
    "taught": "VB",
    "teaching": "VB",
    "teaches": "VB",
    "theory": "VB",
    "theorized": "VB",
    "theorizing": "VB",
    "theories": "VB",
    "unify": "VB",
    "unified": "VB",
    "unifying": "VB",
    "unifies": "VB",
    "wiki building": "VB",
    "wiki built": "VB",
    "wiki builds": "VB",
    "write": "VB",
    "wrote": "VB",
    "writing": "VB",
    "writes": "VB",
}
